### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by gblmarquez** [lfreneda/Cielo#2]
Olá @lfreneda,

Primeiramente parabéns pela qualidade da biblioteca.

Que tal criarmos uma package no nuget? Acho que dará a biblioteca muito mais visão, por outros desenvolvedores.

Abraços,

Gabriel Marquez

**Comment by lfreneda** [comment]
1 ano depois..

http://www.nuget.org/packages/Cielo/

Sorry about that, D:

Recebi um pull request bem legal que me animou :smiley:
