### ISSUE TITLE
parcelamento

### ISSUE THREAD

**Issue by eltonnakamura** [lfreneda/Cielo#7]
e no caso de compras com valor total parcelado, é possivel? pq quase ninguem hoje paga a vista...

**Comment by lfreneda** [comment]
@eltonnakamura tudo bem?

Quando comecei a implementar a integração com a Cielo foi para empresa na qual estava trabalhando (LevelUp Games), lá não iriamos usar parcelamento, então acabei não testando essa opção.

Porém, acredito que a implementação contemplou parcelamento sim (preciso tirar do README o aviso)

Tanto que até mandaram um pull request com o exemplo de como parcelar:

https://github.com/lfreneda/Cielo/blob/master/samples/Cielo.Web.Sample/Controllers/CieloBuyPageCartController.cs#L47-L49

O que eu aconselho você fazer, é testar de forma integrada com a Cielo a opção de parcalamento.

Fique a vontade para contribuir com o projeto :dancers: 

Qualquer dúvida só mandar aqui :+1:

**Comment by eltonnakamura** [comment]
caraiii que rapidez a sua!!! vou ver entao e qualquer coisa te aviso ae...obrigado por enquanto!

**Comment by lfreneda** [comment]
@eltonnakamura :wink:

Qualquer coisa, só falar
