### ISSUE TITLE
Versão do webservice Cielo

### ISSUE THREAD

**Issue by cBarbosa** [lfreneda/Cielo#9]
Saudações,

Esta sua versão está padronizada com a última versão da Cielo(Versão 3.0)?

Atte,
C S B

**Comment by lfreneda** [comment]
Fala @cBarbosa tudo bem? 

Essa implementação foi feita 2014 ~ e na época, a documentação que a Cielo fornecia era confidencial, então não foi possível versionar junto com o código.

Não acredito que seja padronizada com a versão 3, **nos arquivos xml de exemplos a versão indicada é a 1.3.0**

https://github.com/lfreneda/Cielo/blob/57b3f09d058ba281f63ba14979167b0992d32af7/docs/xml%20samples/requisicao-autorizacao-tid.xml#L2

Grande abraço,
